# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserRegistration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, email: str=None, password: str=None):  # noqa: E501
        """UserRegistration - a model defined in Swagger

        :param name: The name of this UserRegistration.  # noqa: E501
        :type name: str
        :param email: The email of this UserRegistration.  # noqa: E501
        :type email: str
        :param password: The password of this UserRegistration.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'name': str,
            'email': str,
            'password': str
        }

        self.attribute_map = {
            'name': 'name',
            'email': 'email',
            'password': 'password'
        }
        self._name = name
        self._email = email
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'UserRegistration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserRegistration of this UserRegistration.  # noqa: E501
        :rtype: UserRegistration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this UserRegistration.

        Полное имя пользователя  # noqa: E501

        :return: The name of this UserRegistration.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this UserRegistration.

        Полное имя пользователя  # noqa: E501

        :param name: The name of this UserRegistration.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def email(self) -> str:
        """Gets the email of this UserRegistration.

        Электронная почта пользователя  # noqa: E501

        :return: The email of this UserRegistration.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserRegistration.

        Электронная почта пользователя  # noqa: E501

        :param email: The email of this UserRegistration.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def password(self) -> str:
        """Gets the password of this UserRegistration.

        Пароль для учетной записи пользователя  # noqa: E501

        :return: The password of this UserRegistration.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this UserRegistration.

        Пароль для учетной записи пользователя  # noqa: E501

        :param password: The password of this UserRegistration.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password
