name: CI/CD for Flask with Observability

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Запуск тестов
      - name: Run tests
        run: |
          pytest

      # 5. Проверка кода линтером
      - name: Run flake8
        run: |
          pip install flake8
          flake8 .

      # 6. Сборка Docker-контейнеров
      - name: Build Docker Compose services
        run: docker-compose build

      # 7. Логин в Docker Hub 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Пуш Docker-образа
      - name: Push Docker image to DockerHub
        run: docker-compose push

      # 9. Развертывание на сервере
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /path/to/your/project
          git pull
          docker-compose down
          docker-compose up -d
          EOF

